### ISSUE TITLE
Hi i just use this to contact you :)

### ISSUE THREAD

**Issue by ohmcodes** [MartinSGill/Profile#1]
I saw your repo  Subnauticawatcher and  im really amaze about it, i am wondering if you could help me to build my own and i was  thinking to make one for "below zero" just few tips and brief,i guess i can take it from there. thanks i hope you can help me, heres my info
ohmcodes@gmail.com

**Comment by MartinSGill** [comment]
Once the game was out, much better modders created a great map, that I now use myself.
https://www.nexusmods.com/subnautica/mods/12

If you do want to update SubnauticaWatcher for Below Zero, then just fork it and go ahead. There's probably very little that needs changing. Just map images, POI coordinates etc and how it hooks into the game.
